('Peak sachet 16g', 'Peak sachet 16g',
('Peak Baby 400g tin', 'Peak Baby 400g tin',
('Milo Refill 1kg', 'Milo Refill 1kg',
('Milo Refill 500g', 'Milo Refill 500g',
('Milo Refill 200g', 'Milo Refill 200g',
('Milo Refill 20g', 'Milo Refill 20g',
('Milo Tin 1kg', 'Milo Tin 1kg',
('Milo Tin 500g', 'Milo Tin 500g',
('Peak Refill 850g', 'Peak Refill 850g',
('Peak Refill 380g', 'Peak Refill 380g',
('Peak Refill 260g', 'Peak Refill 260g',
('Peak Refill 4-5-6 400g', 'Peak Refill 4-5-6 400g',
('Peak Refill 1-2-3 380g', 'Peak Refill 1-2-3 380g',
('Peak Tin 2500g', 'Peak Tin 2500g',
('Peak Tin 900g', 'Peak Tin 900g',
('Peak Tin 400g', 'Peak Tin 400g',
('Peak Tin 1-2-3 400g', 'Peak Tin 1-2-3 400g',
('Peak Chocolate 3in1 400g ref', 'Peak Chocolate 3in1 400g ref',
('Peak New 160g', 'Peak New 160g',
('Peak Condensed 78g', 'Peak Condensed 78g',
('Three Crown Refill 770g', 'Three Crown Refill 770g',
('Three Crown Refill 350g', 'Three Crown Refill 350g',
('Three Crown 160g', 'Three Crown 160g',
('Moms tomato paste', 'Moms tomato paste',
('Peak Gold 160g', 'Peak Gold 160g',
('Coco Pops Sachet', 'Coco Pops Sachet',
('Nasco Conflakes Sachet', 'Nasco Conflakes Sachet',
('Cerelac Sachet 50g', 'Cerelac Sachet 50g',
('Sunvita Sachet', 'Sunvita Sachet',
('Blue Band sachet 12g', 'Blue Band sachet 12g',
('Nescafe 3 in 1 Sachet', 'Nescafe 3 in 1 Sachet',
('Nescafe Sachet', 'Nescafe Sachet',
('Oluji Pure Cocoa Refill 250g', 'Oluji Pure Cocoa Refill 250g',
('Jago Condensed Milk', 'Jago Condensed Milk',
('Dano Full Cream Refill 360g', 'Dano Full Cream Refill 360g',
('Dano Cool Cow Refill 360g', 'Dano Cool Cow Refill 360g',
('Cowbell Tin 400g', 'Cowbell Tin 400g',
('Hollandia Cap 190g', 'Hollandia Cap 190g',
('Hollandia Evap 120g', 'Hollandia Evap 120g',
('Hollandia Evap 60g', 'Hollandia Evap 60g',
('Bounvita Refill 200g', 'Bounvita Refill 200g',
('Bounvita Refill 20g', 'Bounvita Refill 20g',
('Bournvita Tin 1000g', 'Bournvita Tin 1000g',
('Bournvita Tin 500g', 'Bournvita Tin 500g',
('Munro Corn Flour 350g', 'Munro Corn Flour 350g',
('Sensodyne Daily Care 40ml', 'Sensodyne Daily Care 40ml',
('Sensodyne Gentle Whitening', 'Sensodyne Gentle Whitening',
('Sensodyne Deep Clean 75ml', 'Sensodyne Deep Clean 75ml',
('Sensodyne Daily Care 75ml', 'Sensodyne Daily Care 75ml',
('Sensodyne Extra Fresh 75ml', 'Sensodyne Extra Fresh 75ml',
('Macleans Milk Teeth 1-6years', 'Macleans Milk Teeth 1-6years',
('Macleans  Herbal', 'Macleans  Herbal',
('Macleans Complete Care B/S', 'Macleans Complete Care B/S',
('Close Up 140g', 'Close Up 140g',
('Macleans Compute Care S/S 50ml', 'Macleans Compute Care S/S 50ml',
('Oral B Family Size', 'Oral B Family Size',
('Pepsodent 1-2-3 75g', 'Pepsodent 1-2-3 75g',
('Close Up sachet 25g', 'Close Up sachet 25g',
('Diplomat Exotic Tooth Brush', 'Diplomat Exotic Tooth Brush',
('Oral Wise Tooth Brush', 'Oral Wise Tooth Brush',
('Lucky Dog Tooth Brush', 'Lucky Dog Tooth Brush', 
('Chery Gold Tooth Brush', 'Chery Gold Tooth Brush', 
('Wisdom Tooth Brush', 'Wisdom Tooth Brush', 
('Brown Envelope ', 'Brown Envelope ', 
('sasi soap', 'sasi soap', 
('Oxford Maths Set', 'Oxford Maths Set', 
('Unique K Math Set', 'Unique K Math Set', 
('Diplomat VIP ', 'Diplomat VIP ', 
('Best Foot Ruler B/S', 'Best Foot Ruler B/S', 
('Best Foot Ruler S/S', 'Best Foot Ruler S/S', 
('Fine Glue', 'Fine Glue', 
('Afrostic Price Tag', 'Afrostic Price Tag', 
('Blessed Assurance Invoice', 'Blessed Assurance Invoice', 
('My School Book 2D/2B', 'My School Book 2D/2B', 
('Rocher tomato paste', 'Rocher tomato paste', 
('Campus Note Book (60L)', 'Campus Note Book (60L)', 
('Igle Correction Pen', 'Igle Correction Pen', 
('Monami White Marker', 'Monami White Marker', 
('Maple Leaf Note Book (40L)', 'Maple Leaf Note Book (40L)', 
('Campus Higher Education (80L)', 'Campus Higher Education (80L)', 
('Permanent Maker ', 'Permanent Maker ', 
('White Envelope', 'White Envelope', 
('Diplomatic Comfort Tooth Brush', 'Diplomatic Comfort Tooth Brush', 
('Diplomatic Select Tooth Brush', 'Diplomatic Select Tooth Brush', 
('Diplomatic Dominion Tooth Brush', 'Diplomatic Dominion Tooth Brush', 
('Diplomatic Sporting', 'Diplomatic Sporting', 
('King Lion Drawing Book', 'King Lion Drawing Book', 
('Image Graph Book', 'Image Graph Book', 
('Document File B/S', 'Document File B/S', 
('Document File S/S', 'Document File S/S', 
('Diplomatic Senator', 'Diplomatic Senator', 
('My My Matches', 'My My Matches', 
('Herbal Aloe Vera powerd', 'Herbal Aloe Vera powerd', 
('Andrews Liver Salts', 'Andrews Liver Salts', 
('Ovaltine Tin B/S (1200g)', 'Ovaltine Tin B/S (1200g)', 
('Ovaltine Tin S/S (400g)', 'Ovaltine Tin S/S (400g)', 
('Jago drinking Chocolate B/s', 'Jago drinking Chocolate B/s', 
('Jago Drinking Chocolate S/S', 'Jago Drinking Chocolate S/S', 
('St Loius Sugar', 'St Loius Sugar', 
('Lipton YellowTea', 'Lipton YellowTea', 
('Glen Black Tea', 'Glen Black Tea', 
('Hilly Way Gold Labal', 'Hilly Way Gold Labal', 
('Rose Garla tissu S/S', 'Rose Garla tissu S/S', 
('Short Bread Fingers', 'Short Bread Fingers', 
('Mactivites Short bread B/S', 'Mactivites Short bread B/S', 
('Mactivites Short bread S/S', 'Mactivites Short bread S/S', 
('Mactivites Hobnobs 300g', 'Mactivites Hobnobs 300g', 
('Mactivites Digestives B/S 250g', 'Mactivites Digestives B/S 250g', 
('Rich Tea B/S 300g', 'Rich Tea B/S 300g', 
('Rich Tea S/S 200g', 'Rich Tea S/S 200g', 
('Milk Soda Cracker B/S 248g', 'Milk Soda Cracker B/S 248g', 
('Milk Soda Cracker S/S 100g', 'Milk Soda Cracker S/S 100g', 
('Mactivites Digestive S/S 200g', 'Mactivites Digestive S/S 200g', 
('Leo Milk Stick', 'Leo Milk Stick', 
('Malkest Crackers', 'Malkest Crackers', 
('Bottle Grandnut', 'Bottle Grandnut', 
('Da-ray Bee Honey B/S', 'Da-ray Bee Honey B/S', 
('Da-ray Bee Honey M/S', 'Da-ray Bee Honey M/S', 
('Da-ray Bee Honey s/S', 'Da-ray Bee Honey s/S', 
('Vitali Margarine', 'Vitali Margarine', 
('Blue Band S/S 250g', 'Blue Band S/S 250g', 
('Bama Mayonnaise B/S 946ml', 'Bama Mayonnaise B/S 946ml', 
('Bama Mayonnaise S/S 473ml', 'Bama Mayonnaise S/S 473ml', 
('Aromate Mayonnaise M/S 270ml', 'Aromate Mayonnaise M/S 270ml', 
('Maggi Signatur Jollof', 'Maggi Signatur Jollof', 
('Bua Paste Macaroni', 'Bua Paste Macaroni', 
('Lucia Macaroni', 'Lucia Macaroni', 
('Matanti Macaroni', 'Matanti Macaroni', 
('Flutes', 'Flutes', 
('Cabin Biscuits', 'Cabin Biscuits', 
('Bonita Spaghetti', 'Bonita Spaghetti', 
('Hutesa Spanish Olives', 'Hutesa Spanish Olives', 
('Mr. Chef Salt 1kg', 'Mr. Chef Salt 1kg', 
('Mr. Chef Salt 500g', 'Mr. Chef Salt 500g', 
('Mr. Chef Salt 250g', 'Mr. Chef Salt 250g', 
('Maggi Star Seasoning 400g', 'Maggi Star Seasoning 400g', 
('Alubadiya Season Poweder', 'Alubadiya Season Poweder', 
('Maggi crayfish 600g', 'Maggi crayfish 600g', 
('Bestotes Maggi', 'Bestotes Maggi', 
('La Flor Thyme', 'La Flor Thyme', 
('La Flor Curry Powder', 'La Flor Curry Powder', 
('La Flor Cinnamon Sticks', 'La Flor Cinnamon Sticks', 
('La Flor Whole Oregano', 'La Flor Whole Oregano', 
('La Flor Chu Powder', 'La Flor Chu Powder', 
('La Flor All Mix Seasoning', 'La Flor All Mix Seasoning', 
('La Flor Garlic Powder', 'La Flor Garlic Powder', 
('La Flor Chicken', 'La Flor Chicken', 
('La Flor Steak Seasoning', 'La Flor Steak Seasoning', 
('Titus', 'Titus', 
('Bonjourne By Mr Cools sardines', 'Bonjourne By Mr Cools sardines', 
('Milo sardines', 'Milo sardines', 
('Napa Sardines', 'Napa Sardines', 
('Mr. Cook tin tomato', 'Mr. Cook tin tomato', 
('Spicity Seasoning Powder', 'Spicity Seasoning Powder', 
('Nora Spice Fried Rice', 'Nora Spice Fried Rice', 
('Royco Seasoning', 'Royco Seasoning', 
('Real Red Beans', 'Real Red Beans', 
('Farmers Peas', 'Farmers Peas', 
('Rayners Vanilla flavour /strawberry', 'Rayners Vanilla flavour /strawberry', 
('Moulinex Blender', 'Moulinex Blender', 
('Moulinex Toaster', 'Moulinex Toaster', 
('Camelot Glass Cup 4pcs', 'Camelot Glass Cup 4pcs', 
('Borgonovo 3pcs B/S', 'Borgonovo 3pcs B/S', 
('Borgonovo jazz 3pcs S/S', 'Borgonovo jazz 3pcs S/S', 
('Borgonovo 2pcs B/S', 'Borgonovo 2pcs B/S', 
('Borgonovo 4pcs', 'Borgonovo 4pcs', 
('Borgonovo 6pcs', 'Borgonovo 6pcs', 
('Ducale Cup 4pcs ', 'Ducale Cup 4pcs ', 
('Ducale Cup 6pcs 31', 'Ducale Cup 6pcs 31', 
('Ducale Cup 6pcs 17', 'Ducale Cup 6pcs 17', 
('Soehnle Weight Checker scale', 'Soehnle Weight Checker scale', 
('Enacta Digital Glass Personal Scale', 'Enacta Digital Glass Personal Scale', 
('Tefal Cooking Port 6.3L', 'Tefal Cooking Port 6.3L', 
('Tefal Cooking Port 7.8L', 'Tefal Cooking Port 7.8L', 
('Tefal Frying Pan 2.8L', 'Tefal Frying Pan 2.8L', 
('Tefal Frying Pan 24cm', 'Tefal Frying Pan 24cm', 
('Tefal Frying Pan 0.5cm', 'Tefal Frying Pan 0.5cm', 
('Tefal Cooking Port 11.6L', 'Tefal Cooking Port 11.6L', 
('Tefal Cooking Port 4.7L', 'Tefal Cooking Port 4.7L', 
('Leifheit Jug 1L', 'Leifheit Jug 1L', 
('Leifheit Jug 0.5L', 'Leifheit Jug 0.5L', 
('Simbelt Family Utensil', 'Simbelt Family Utensil', 
('Cadle to Cadle Bronze', 'Cadle to Cadle Bronze', 
('Master Chef (School Lunch Set)', 'Master Chef (School Lunch Set)', 
('Ceramic Set 5(4mug 1jug)', 'Ceramic Set 5(4mug 1jug)', 
('Kechuang Food Flask 800ML', 'Kechuang Food Flask 800ML', 
('G and L Cutlery Set 24pcs', 'G and L Cutlery Set 24pcs', 
('Angel Baby Wipes 250Pop-pus', 'Angel Baby Wipes 250Pop-pus', 
('Angel Baby Wipes 100Pop-pus', 'Angel Baby Wipes 100Pop-pus', 
('Aveat New Born Starter Set (8Pieces)', 'Aveat New Born Starter Set (8Pieces)', 
('Carter Baby Shoe', 'Carter Baby Shoe', 
('Duremi Aromatherapy Baby Care', 'Duremi Aromatherapy Baby Care', 
('Baby Sweet Mug', 'Baby Sweet Mug', 
('Famera Powder Puff', 'Famera Powder Puff', 
('Kings cooking margarin 250g', 'Kings cooking margarin 250g', 
('Borganovo cup 6pcs 280', 'Borganovo cup 6pcs 280', 
('Smile Bear', 'Smile Bear', 
('Baby Cherie (Cotton Bud)', 'Baby Cherie (Cotton Bud)', 
('Modas Touch (Loose Deep)', 'Modas Touch (Loose Deep)', 
('Modas Touch (Afro B)', 'Modas Touch (Afro B)', 
('Darling', 'Darling', 
('KaneKalon (lowly Piece)', 'KaneKalon (lowly Piece)', 
('Xpression (Liza)', 'Xpression (Liza)', 
('Enjoy Baby Love 50m (Feeding Bottle)', 'Enjoy Baby Love 50m (Feeding Bottle)', 
('Feeding Bottle 250m', 'Feeding Bottle 250m', 
('Milo sweet choco milo', 'Milo sweet choco milo', 
('Tefal Baking tray', 'Tefal Baking tray', 
('Feeding Bottle 60ml', 'Feeding Bottle 60ml', 
('Only Baby Comb', 'Only Baby Comb', 
('Sacvin (Water Bottle)', 'Sacvin (Water Bottle)', 
('Dship (Water Bottle)', 'Dship (Water Bottle)', 
('Enchanteur 250ml cream', 'Enchanteur 250ml cream', 
('Tiger Blade (Pieces)', 'Tiger Blade (Pieces)', 
('HANA Cup (Timble)', 'HANA Cup (Timble)', 
('St. Eve Wine 75cl (Strawberry)', 'St. Eve Wine 75cl (Strawberry)', 
('Glamor Wine 75cl (White Grape)', 'Glamor Wine 75cl (White Grape)', 
('Glamor Wine 75cl (Mixed Fruit) ', 'Glamor Wine 75cl (Mixed Fruit) ', 
('Eloi Wine 75cl', 'Eloi Wine 75cl', 
('Valentino Wine 37.5cl', 'Valentino Wine 37.5cl', 
('Veleta Wine 37.5cl', 'Veleta Wine 37.5cl', 
('Veleta Wine 70cl', 'Veleta Wine 70cl', 
('Valentino Wine 70cl', 'Valentino Wine 70cl', 
('St. Lauren Wine 70cl', 'St. Lauren Wine 70cl', 
('Emas Wine 70cl', 'Emas Wine 70cl', 
('St. Eve Wine 300ml Unit (Strawberry)', 'St. Eve Wine 300ml Unit (Strawberry)', 
('St. Eve Wine 300ml Bulk (Strawberry)', 'St. Eve Wine 300ml Bulk (Strawberry)', 
('Monster Energy Drink Bulk', 'Monster Energy Drink Bulk', 
('Cedar Yoghurt 50cl Bulk (Pineaple)', 'Cedar Yoghurt 50cl Bulk (Pineaple)', 
('Cedar Yoghurt 50cl Bulk (Vanilla)', 'Cedar Yoghurt 50cl Bulk (Vanilla)', 
('Cedar yoghurt(unsweetened) 75cl ', 'Cedar yoghurt(unsweetened) 75cl ', 
('Cedar yoghurt vanilla 75cl ', 'Cedar yoghurt vanilla 75cl ', 
('Havilah zobo 45cl', 'Havilah zobo 45cl', 
('Lucozade 1ltr pet', 'Lucozade 1ltr pet', 
('Golden morn wazobia 35g', 'Golden morn wazobia 35g', 
('Aromate oil 5L', 'Aromate oil 5L', 
('Baby Bed', 'Baby Bed', 
('Abro oil treatment', 'Abro oil treatment', 
('Abrosmoke stop', 'Abrosmoke stop', 
('Stop(oil treatment)', 'Stop(oil treatment)', 
('Lily pencil(Pack)', 'Lily pencil(Pack)', 
('Guhwa pencil(pacK)', 'Guhwa pencil(pacK)', 
('Guhwa pencil(unpacK)', 'Guhwa pencil(unpacK)', 
('Paper tape', 'Paper tape', 
('lynon(Big) tape', 'lynon(Big) tape', 
('lynon(small) tape', 'lynon(small) tape', 
('Avanti pen(magna)', 'Avanti pen(magna)', 
('Avanti pen(silver stripes)', 'Avanti pen(silver stripes)', 
('Skintex male condom', 'Skintex male condom', 
('Fire xtacy', 'Fire xtacy', 
('Gold circle', 'Gold circle', 
('Dark and lovely(professional Exxertize)', 'Dark and lovely(professional Exxertize)', 
('Dark and lovely(beautiful beginning)', 'Dark and lovely(beautiful beginning)', 